[tool.poetry]
name = "lisa"
version = "0.1.0"
description = ""
authors = ["daniel kostin <dikostin@edu.hse.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
